// @procella/types — Pulumi wire protocol types.
//
// Types are generated by tygo from the Pulumi SDK's Go apitype package
// (github.com/pulumi/pulumi/sdk/v3/go/common/apitype).
//
// This file selectively re-exports only the types needed for our self-hosted
// backend, and adds const enum objects for type-safe enum usage.
//
// To regenerate: bun run types:generate

import type { DeploymentV3, OperationV2, ResourceV3, SecretsProvidersV1 } from "./pulumi.gen.js";

// Re-export all types we need from the tygo-generated file.
// The .gen.ts file is excluded from Biome linting but still type-checked by tsc.
// Re-export type aliases
export type {
	// Update types (updates.go)
	AISettingsForUpdate,
	APICapability,
	// Service / capability types (service.go)
	APICapabilityConfig,
	AppendUpdateLogEntryRequest,
	// Stack types (stacks.go)
	BatchDecryptRequest,
	BatchDecryptResponse,
	BatchEncryptRequest,
	BatchEncryptResponse,
	// Event types (events.go)
	CancelEvent,
	CapabilitiesResponse,
	// CLI types (cli.go)
	CLIVersionResponse,
	CompleteUpdateRequest,
	// Core types (core.go)
	ConfigValue,
	CreateStackRequest,
	CreateStackResponse,
	CreateUpdateConfig,
	DecryptValueRequest,
	DecryptValueResponse,
	DeltaCheckpointUploadsConfigV2,
	DeploymentSchemaVersionConfig,
	// Deployment / resource types (core.go)
	DeploymentV3,
	DiagnosticEvent,
	EncryptValueRequest,
	EncryptValueResponse,
	EngineEvent,
	EngineEventBatch,
	ErrorEvent,
	// Error types (errors.go)
	ErrorResponse,
	ExportStackResponse,
	// History types (history.go)
	GetHistoryResponse,
	GetUpdateEventsResponse,
	ImportStackRequest,
	ImportStackResponse,
	ListStacksResponse,
	Log3rdPartyDecryptionEvent,
	ManifestV1,
	Message,
	OperationStatus,
	OperationV2,
	PatchUpdateCheckpointDeltaRequest,
	PatchUpdateCheckpointRequest,
	PatchUpdateVerbatimCheckpointRequest,
	PluginInfoV1,
	PolicyAnalyzeStackSummaryEvent,
	PolicyAnalyzeSummaryEvent,
	PolicyEvent,
	PolicyLoadEvent,
	PolicyRemediateSummaryEvent,
	PolicyRemediationEvent,
	PreludeEvent,
	ProgressEvent,
	PropertyDiff,
	RenewUpdateLeaseRequest,
	RenewUpdateLeaseResponse,
	RequestError,
	// Policy types (policy.go)
	RequiredPolicy,
	ResOpFailedEvent,
	ResOutputsEvent,
	ResourcePreEvent,
	ResourceV3,
	SecretsProvidersV1,
	Stack,
	StackConfig,
	StackLinks,
	StackRenameRequest,
	StackSummary,
	StackTagName,
	StartDebuggingEvent,
	StartUpdateRequest,
	StartUpdateResponse,
	StdoutEngineEvent,
	StepEventMetadata,
	StepEventStateMetadata,
	SummaryEvent,
	UntypedDeployment,
	UpdateEvent,
	UpdateInfo,
	UpdateMetadata,
	UpdateOptions,
	UpdateProgramRequest,
	UpdateProgramResponse,
	UpdateResults,
	VersionedCheckpoint,
} from "./pulumi.gen.js";

// Re-export useful constants
export {
	DeploymentSchemaVersionCurrent,
	DeploymentSchemaVersionLatest,
	ProjectDescriptionTag,
	ProjectNameTag,
	ProjectRuntimeTag,
	ProjectTemplateTag,
} from "./pulumi.gen.js";

// ============================================================================
// Enum allowlists (as const + type union pattern)
// ============================================================================

export const UPDATE_KINDS = ["update", "preview", "refresh", "destroy", "import"] as const;
export type UpdateKind = (typeof UPDATE_KINDS)[number];

export function isValidUpdateKind(s: string): s is UpdateKind {
	return (UPDATE_KINDS as readonly string[]).includes(s);
}

export const UpdateResult = {
	NotStarted: "not-started",
	InProgress: "in-progress",
	Succeeded: "succeeded",
	Failed: "failed",
} as const;
export type UpdateResult = (typeof UpdateResult)[keyof typeof UpdateResult];

export const OpType = {
	Same: "same",
	Create: "create",
	Update: "update",
	Delete: "delete",
	Replace: "replace",
	CreateReplacement: "create-replacement",
	DeleteReplaced: "delete-replaced",
	Read: "read",
	ReadReplacement: "read-replacement",
	Refresh: "refresh",
	ReadDiscard: "discard",
	DiscardReplaced: "discard-replaced",
	RemovePendingReplace: "remove-pending-replace",
	Import: "import",
	ImportReplacement: "import-replacement",
} as const;
export type OpType = (typeof OpType)[keyof typeof OpType];

export const UpdateStatus = {
	NotStarted: "not started",
	Requested: "requested",
	Running: "running",
	Failed: "failed",
	Succeeded: "succeeded",
	Cancelled: "cancelled",
} as const;
export type UpdateStatus = (typeof UpdateStatus)[keyof typeof UpdateStatus];

export const UpdateEventKind = {
	Stdout: "stdout",
	Stderr: "stderr",
} as const;
export type UpdateEventKind = (typeof UpdateEventKind)[keyof typeof UpdateEventKind];

export const DiffKind = {
	Add: "add",
	AddReplace: "add-replace",
	Delete: "delete",
	DeleteReplace: "delete-replace",
	Update: "update",
	UpdateReplace: "update-replace",
} as const;
export type DiffKind = (typeof DiffKind)[keyof typeof DiffKind];

export const ProgressType = {
	PluginDownload: "plugin-download",
	PluginInstall: "plugin-install",
} as const;
export type ProgressType = (typeof ProgressType)[keyof typeof ProgressType];

export const MessageSeverity = {
	Warning: "warning",
	Error: "error",
	Info: "info",
} as const;
export type MessageSeverity = (typeof MessageSeverity)[keyof typeof MessageSeverity];

export const ErrorType = {
	NotFound: "not_found",
	Required: "required",
	Invalid: "invalid",
	AlreadyExists: "already_exists",
	Custom: "custom",
} as const;
export type ErrorType = (typeof ErrorType)[keyof typeof ErrorType];

export const OperationType = {
	Creating: "creating",
	Updating: "updating",
	Deleting: "deleting",
	Reading: "reading",
} as const;
export type OperationType = (typeof OperationType)[keyof typeof OperationType];

// ============================================================================
// Journal types — hand-written (not generated by tygo; journal.go is a
// separate Pulumi SDK package outside the apitype package tygo targets).
// These types mirror github.com/pulumi/pulumi/sdk/v3/go/common/apitype/journal.go
// ============================================================================

export type JournalEntryKind = number;

export const JournalEntryBegin: JournalEntryKind = 0;
export const JournalEntrySuccess: JournalEntryKind = 1;
export const JournalEntryFailure: JournalEntryKind = 2;
export const JournalEntryRefreshSuccess: JournalEntryKind = 3;
export const JournalEntryOutputs: JournalEntryKind = 4;
export const JournalEntryWrite: JournalEntryKind = 5;
export const JournalEntrySecretsManager: JournalEntryKind = 6;
export const JournalEntryRebuiltBaseState: JournalEntryKind = 7;

export interface JournalEntry {
	version: number;
	kind: JournalEntryKind;
	operationID: number;
	sequenceID: number;
	removeOld?: number | null;
	removeNew?: number | null;
	state?: ResourceV3;
	operation?: OperationV2;
	secretsProvider?: SecretsProvidersV1;
	pendingReplacementOld?: number | null;
	pendingReplacementNew?: number | null;
	deleteOld?: number | null;
	deleteNew?: number | null;
	isRefresh?: boolean;
	newSnapshot?: DeploymentV3;
	elideWrite?: boolean;
}

export interface JournalEntries {
	entries?: JournalEntry[];
}
